require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DpmsController do

  # This should return the minimal set of attributes required to create a valid
  # Dpm. As you add validations to Dpm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DpmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dpms as @dpms" do
      dpm = Dpm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dpms).should eq([dpm])
    end
  end

  describe "GET show" do
    it "assigns the requested dpm as @dpm" do
      dpm = Dpm.create! valid_attributes
      get :show, {:id => dpm.to_param}, valid_session
      assigns(:dpm).should eq(dpm)
    end
  end

  describe "GET new" do
    it "assigns a new dpm as @dpm" do
      get :new, {}, valid_session
      assigns(:dpm).should be_a_new(Dpm)
    end
  end

  describe "GET edit" do
    it "assigns the requested dpm as @dpm" do
      dpm = Dpm.create! valid_attributes
      get :edit, {:id => dpm.to_param}, valid_session
      assigns(:dpm).should eq(dpm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dpm" do
        expect {
          post :create, {:dpm => valid_attributes}, valid_session
        }.to change(Dpm, :count).by(1)
      end

      it "assigns a newly created dpm as @dpm" do
        post :create, {:dpm => valid_attributes}, valid_session
        assigns(:dpm).should be_a(Dpm)
        assigns(:dpm).should be_persisted
      end

      it "redirects to the created dpm" do
        post :create, {:dpm => valid_attributes}, valid_session
        response.should redirect_to(Dpm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dpm as @dpm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dpm.any_instance.stub(:save).and_return(false)
        post :create, {:dpm => {  }}, valid_session
        assigns(:dpm).should be_a_new(Dpm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dpm.any_instance.stub(:save).and_return(false)
        post :create, {:dpm => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dpm" do
        dpm = Dpm.create! valid_attributes
        # Assuming there are no other dpms in the database, this
        # specifies that the Dpm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dpm.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => dpm.to_param, :dpm => { "these" => "params" }}, valid_session
      end

      it "assigns the requested dpm as @dpm" do
        dpm = Dpm.create! valid_attributes
        put :update, {:id => dpm.to_param, :dpm => valid_attributes}, valid_session
        assigns(:dpm).should eq(dpm)
      end

      it "redirects to the dpm" do
        dpm = Dpm.create! valid_attributes
        put :update, {:id => dpm.to_param, :dpm => valid_attributes}, valid_session
        response.should redirect_to(dpm)
      end
    end

    describe "with invalid params" do
      it "assigns the dpm as @dpm" do
        dpm = Dpm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dpm.any_instance.stub(:save).and_return(false)
        put :update, {:id => dpm.to_param, :dpm => {  }}, valid_session
        assigns(:dpm).should eq(dpm)
      end

      it "re-renders the 'edit' template" do
        dpm = Dpm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dpm.any_instance.stub(:save).and_return(false)
        put :update, {:id => dpm.to_param, :dpm => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dpm" do
      dpm = Dpm.create! valid_attributes
      expect {
        delete :destroy, {:id => dpm.to_param}, valid_session
      }.to change(Dpm, :count).by(-1)
    end

    it "redirects to the dpms list" do
      dpm = Dpm.create! valid_attributes
      delete :destroy, {:id => dpm.to_param}, valid_session
      response.should redirect_to(dpms_url)
    end
  end

end
