require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MatMembershipsController do

  # This should return the minimal set of attributes required to create a valid
  # MatMembership. As you add validations to MatMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "material_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatMembershipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mat_memberships as @mat_memberships" do
      mat_membership = MatMembership.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mat_memberships).should eq([mat_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested mat_membership as @mat_membership" do
      mat_membership = MatMembership.create! valid_attributes
      get :show, {:id => mat_membership.to_param}, valid_session
      assigns(:mat_membership).should eq(mat_membership)
    end
  end

  describe "GET new" do
    it "assigns a new mat_membership as @mat_membership" do
      get :new, {}, valid_session
      assigns(:mat_membership).should be_a_new(MatMembership)
    end
  end

  describe "GET edit" do
    it "assigns the requested mat_membership as @mat_membership" do
      mat_membership = MatMembership.create! valid_attributes
      get :edit, {:id => mat_membership.to_param}, valid_session
      assigns(:mat_membership).should eq(mat_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MatMembership" do
        expect {
          post :create, {:mat_membership => valid_attributes}, valid_session
        }.to change(MatMembership, :count).by(1)
      end

      it "assigns a newly created mat_membership as @mat_membership" do
        post :create, {:mat_membership => valid_attributes}, valid_session
        assigns(:mat_membership).should be_a(MatMembership)
        assigns(:mat_membership).should be_persisted
      end

      it "redirects to the created mat_membership" do
        post :create, {:mat_membership => valid_attributes}, valid_session
        response.should redirect_to(MatMembership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mat_membership as @mat_membership" do
        # Trigger the behavior that occurs when invalid params are submitted
        MatMembership.any_instance.stub(:save).and_return(false)
        post :create, {:mat_membership => { "material_id" => "invalid value" }}, valid_session
        assigns(:mat_membership).should be_a_new(MatMembership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MatMembership.any_instance.stub(:save).and_return(false)
        post :create, {:mat_membership => { "material_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mat_membership" do
        mat_membership = MatMembership.create! valid_attributes
        # Assuming there are no other mat_memberships in the database, this
        # specifies that the MatMembership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MatMembership.any_instance.should_receive(:update).with({ "material_id" => "1" })
        put :update, {:id => mat_membership.to_param, :mat_membership => { "material_id" => "1" }}, valid_session
      end

      it "assigns the requested mat_membership as @mat_membership" do
        mat_membership = MatMembership.create! valid_attributes
        put :update, {:id => mat_membership.to_param, :mat_membership => valid_attributes}, valid_session
        assigns(:mat_membership).should eq(mat_membership)
      end

      it "redirects to the mat_membership" do
        mat_membership = MatMembership.create! valid_attributes
        put :update, {:id => mat_membership.to_param, :mat_membership => valid_attributes}, valid_session
        response.should redirect_to(mat_membership)
      end
    end

    describe "with invalid params" do
      it "assigns the mat_membership as @mat_membership" do
        mat_membership = MatMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MatMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => mat_membership.to_param, :mat_membership => { "material_id" => "invalid value" }}, valid_session
        assigns(:mat_membership).should eq(mat_membership)
      end

      it "re-renders the 'edit' template" do
        mat_membership = MatMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MatMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => mat_membership.to_param, :mat_membership => { "material_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mat_membership" do
      mat_membership = MatMembership.create! valid_attributes
      expect {
        delete :destroy, {:id => mat_membership.to_param}, valid_session
      }.to change(MatMembership, :count).by(-1)
    end

    it "redirects to the mat_memberships list" do
      mat_membership = MatMembership.create! valid_attributes
      delete :destroy, {:id => mat_membership.to_param}, valid_session
      response.should redirect_to(mat_memberships_url)
    end
  end

end
